import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[shell]

program = "/bin/zsh"
args = ["-l"]

[font]

normal.family = "CaskaydiaCove Nerd Font Propo"
bold.family = "CaskaydiaCove Nerd Font Propo"
italic.family = "CaskaydiaCove Nerd Font Propo"
bold_italic.family = "CaskaydiaCove Nerd Font Propo"
builtin_box_drawing = false

size = 16.0

[window]

# opacity = 0.9
startup_mode = "Maximized"
# blur = true

[mouse]

hide_when_typing = true
