# === If im planning to change themes with dark and white ===
# TODO
# - Need to create .sh file
#
# 1. alacritty it self
# 2. Zellij
# 3. neo vim

import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[shell]

program = "/bin/zsh"
args = ["-l"]

[font]

normal.family = "FiraCode Nerd Font Propo"
normal.style = "SemiBold"
bold.family = "FiraCode Nerd Font Propo"
italic.family = "FiraCode Nerd Font Propo"
bold_italic.family = "FiraCode Nerd Font Propo"
# normal.style = "Bold"
# bold.family = "CaskaydiaCove Nerd Font Propo"
# italic.family = "CaskaydiaCove Nerd Font Propo"
# bold_italic.family = "CaskaydiaCove Nerd Font Propo"

size = 13.0

[window]

startup_mode = "Maximized"

[mouse]

hide_when_typing = true
