import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[shell]

program = "/bin/zsh"
args = ["-l"]

[font]

normal.family = "CaskaydiaCove Nerd Font Propo"
bold.family = "CaskaydiaCove Nerd Font Propo"
italic.family = "CaskaydiaCove Nerd Font Propo"
bold_italic.family = "CaskaydiaCove Nerd Font Propo"

size = 15.0

[window]

# opacity = 0.8
startup_mode = "Maximized"
blur = true

[mouse]

hide_when_typing = true
