onboarding = false

[worktrees]
directory = "~/.herdr/worktrees"

[session]
resume_agents_on_restore = true

[remote]
manage_ssh_config = true

[ui]
sidebar_width = 50
sidebar_min_width = 50
sidebar_max_width = 50
mouse_capture = true
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true

[ui.sidebar.agents]
row_gap = 1

[ui.sidebar.spaces]
row_gap = 1

[ui.toast]
delivery = "system"
delay_seconds = 1

[keys]
prefix = "ctrl+s"
open_worktree = ""
rename_pane = ""
remove_worktree = "prefix+alt+d"
previous_workspace = "prefix+shift+left"
next_workspace = "prefix+shift+right"
switch_workspace = "prefix+shift+1..9"
previous_agent = "prefix+alt+0"
navigate_workspace_up = "k"
navigate_workspace_down = "j"

[[keys.command]]
key = "prefix+shift+o"
type = "popup"
command = "/Users/cataengineer/.config/herdr/scripts/open-worktree-branch-or-pr"
description = "open worktree, remote branch, or PR"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+shift+p"
type = "popup"
command = "printf 'Workspace directory: '; read dir; [ -n \"$dir\" ] && herdr workspace create --cwd \"$dir\" --label \"$(basename \"$dir\")\""
description = "new workspace from input dir"

[[keys.command]]
key = "prefix+shift+a"
type = "popup"
command = "/Users/cataengineer/.config/herdr/scripts/send-active-buffer-to-agent"
description = "send context curr pane"
width = "60%"
height = "60%"

[[keys.command]]
key = "prefix+shift+u"
type = "shell"
command = "/Users/cataengineer/.config/herdr/scripts/open-current-pr"
description = "open curr PR in browser"

[[keys.command]]
key = "prefix+shift+y"
type = "shell"
command = "/Users/cataengineer/.config/herdr/scripts/sync-all-pr-worktree-labels"
description = "sync all PR worktree labels"

[[keys.command]]
key = "prefix+shift+s"
type = "shell"
command = "/Users/cataengineer/.config/herdr/scripts/sort-workspaces"
description = "sort workspaces alphabetically"

[theme]
name = "dracula"
auto_switch = false
